spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reportsdb}}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${PORT:8080}

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

app:
  jwt:
    secret: ${JWT_SECRET:change-me-please-change-me-please-change-me}
    expirationMillis: ${JWT_EXPIRATION_MILLIS:86400000}